### ISSUE TITLE
FR: make the repo easy to add

### ISSUE THREAD

**Issue by chemelli74** [evgeni/esphome-somfy#113]
Hi,

if you create the following repo structure:

esphome-configs/components/somfy_cover/

(ref. https://esphome.io/components/external_components.html# )

Then the repo can be easily added with the following code:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/evgeni/esphome-configs/components
    components: [ somfy_cover ]
```

Hope you can consider this request.
