### ISSUE TITLE
Compile error : esphome v2023.2.4 + Doubt about wiring

### ISSUE THREAD

**Issue by Briochorama** [evgeni/esphome-somfy#13]
Hi,

First, thanks a lot for the detailed article and configs you shared. I'm having trouble compiling with ESPHome.

Here's the error message I'm getting :

```
In file included from src/main.cpp:34:
src/somfy_cover.h:16:3: error: 'NVSRollingCodeStorage' does not name a type; did you mean 'RollingCodeStorage'?
   16 |   NVSRollingCodeStorage *storage;
      |   ^~~~~~~~~~~~~~~~~~~~~
      |   RollingCodeStorage
src/somfy_cover.h: In constructor 'SomfyESPCover::SomfyESPCover(const char*, const char*, uint32_t)':
src/somfy_cover.h:21:5: error: 'storage' was not declared in this scope
   21 |     storage = new NVSRollingCodeStorage(name, key);
      |     ^~~~~~~
src/somfy_cover.h:21:19: error: expected type-specifier before 'NVSRollingCodeStorage'
   21 |     storage = new NVSRollingCodeStorage(name, key);
      |                   ^~~~~~~~~~~~~~~~~~~~~
/config/esphome/d1mini-02.yaml: In lambda function:
/config/esphome/d1mini-02.yaml:59:37: warning: 'void esphome::cover::Cover::stop()' is deprecated: stop() is deprecated, use make_call().set_command_stop() instead. [-Wdeprecated-declarations]
   59 |           ((SomfyESPCover*)id(somfy))->stop();
      |                                     ^
In file included from src/esphome/core/controller.h:14,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/cover/cover.h:146:8: note: declared here
  146 |   void stop();
      |        ^~~~
Archiving /data/d1mini-02/.pioenvs/d1mini-02/lib67b/libESP8266WiFi.a
*** [/data/d1mini-02/.pioenvs/d1mini-02/src/main.cpp.o] Error 1

```
It looks like ... well actually I'm not so sure what I'm looking at, but a few google searches make me think it's related to newer versions of ESPhome having differents requirements than the one you're using with your config.

Btw, mine is looking like so :

```
esphome:
  name: d1mini-02
  friendly_name: d1mini_02
  includes:
    - components/somfy_secrets.h
    - components/somfy_cover.h
  libraries:
    - EEPROM
    - SPI
    - SmartRC-CC1101-Driver-Lib@2.5.6
    - Somfy_Remote_Lib@0.4.1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

cover:
  - platform: custom
    lambda: |-
      auto somfy_remote = new SomfyESPRemote();
      somfy_remote->add_cover("somfy", "auvent", SOMFY_REMOTE_AUVENT);
      App.register_component(somfy_remote);
      return somfy_remote->covers;
    covers:
      - id: "somfy"
        name: "Somfy Cover"

switch:
  - platform: template
    name: "PROG"
    turn_on_action:
      - lambda: |-
          ((SomfyESPCover*)id(somfy))->program();
  - platform: template
    name: "STOP"
    turn_on_action:
      - lambda: |-
          ((SomfyESPCover*)id(somfy))->stop();
```

I do have somfy.h and somfy_secrets.h placed inside a folder name _components_ in my esphome folder.

As a sidequestion, since I'm pretty sure it's going to cause issue as well : I've read (numerous times) your article, and [you shared the link to a repo with wiring instructions related to a _d1 mini_ board](https://github.com/LSatan/SmartRC-CC1101-Driver-Lib/blob/master/img/Esp8266_CC1101.png). Can I use the same wiring with your code ? Booting with D8 (CSN) on high crashes the _D1 mini_. Is that something I should be worried about ?

**Comment by evgeni** [comment]
Hmm, I'll try to to compile with a newer esphome later, but the error looks more like it can't find the lib, weird.

As for wiring, I have no d1mini to test, but if the pin doesn't work use a different one and maybe configure that in the lib (I'll have a look if that's needed)

**Comment by evgeni** [comment]
Mhh, looking at d1mini pinout d8 is the correct csn and not sure how to change that

**Comment by evgeni** [comment]
oooh, wait, d1 mini is a 8266, right? that doesn't have NVS! you need to use a different storage

**Comment by evgeni** [comment]
(and I pushed a change for the deprecation warning, but that's just that, a waning)

**Comment by Briochorama** [comment]
Wow, thanks for you prompt feedback ! You're right, D1 is a 8266 board. For what it's worth, I've successfully used a CC1101 module with esphome on this board, with the following code. Note that CSN has been changed to D3 

```
esphome:
  name: d1_mini-01
  friendly_name: d1_mini-01
  includes:
    - components/cc1101.h
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"
esp8266:
  board: d1_mini

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        D5, // SCK
        D6, // MISO
        D7, // MOSI
        D3, // CSN
        D1, // GDO0
        D2, // GDO2
        200, // bandwidth_in_khz
        433.92 // freq_in_mhz
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver
      internal: true

remote_transmitter:
  - pin: D2 # This is GDO2
    carrier_duty_percent: 100%

remote_receiver:
  - pin: D1 # This is GDO0
      # on the esp8266 use any of D1,D2,D5,D6,D7,Rx
      # Don't use D3,D4,D8,TX, boot often fails.
      # Can't be D0 or GPIO17 b/c no interrupts
    dump:
      - raw

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "S5HEFkRsuzyqGVKdh/+SWK2rWQhR/++mxeFmZN166t8="

ota:
  password: "ff9f65c88d29824c7da5e094bfdb2dd3"

wifi:
  ssid: "XX"
  password: "XX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu-01 Fallback Hotspot"
    password: "L8xyO3JZbDTx"

web_server:
  port: 80
  
captive_portal:
```

I'm not able to understand your remark able NVS yet. I'll do some digging to understand what's going on.
