### ISSUE TITLE
How to update my ESPHome yaml to get back cover position control?

### ISSUE THREAD

**Issue by stalakerob** [evgeni/esphome-somfy#141]
I have an older implementation of somfy cover. In former versions of home assistant is was possible to control the cover position using "cover.set_cover_position". I have not used this service for quite a while but when I tried today it did not work anymore. I'm getting an error that set_cover_position is not supported by this device. So something in Home Assistant and/or ESPHome must have changed. What do I need to change to make it work again?

This is my ESPHome yaml:
````
esphome:
  name: "markise"
  platform: ESP32
  board: nodemcu-32s
  libraries:
    - EEPROM
    - SPI
    - SmartRC-CC1101-Driver-Lib@2.5.6
    - Somfy_Remote_Lib@0.4.1
  includes:
    - somfy_secrets.h
    - somfy_cover.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.223
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: aio-sensor-ap
    password: !secret ap_fallback_password


captive_portal:

# Enable logging
logger:
  # disbale serial port logging
  baud_rate: 0
  
# Enable Home Assistant API
api:
  reboot_timeout: 60min
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_password

status_led:
  pin: GPIO2

### Pi-Somfy part 
cover:
  - platform: custom
    lambda: |-
      auto somfy_remote = new SomfyESPRemote();
      somfy_remote->add_cover("somfy", "markise", SOMFY_REMOTE_MARKISE);
      App.register_component(somfy_remote);
      return somfy_remote->covers;

    covers:
      - id: "somfy"
        name: "Markise"

switch:
  - platform: template
    name: "Markise PROG"
    turn_on_action:
      - lambda: |-
          ((SomfyESPCover*)id(somfy))->program();
  - platform: template
    name: "Markise STOP"
    turn_on_action:
      - lambda: |-
          ((SomfyESPCover*)id(somfy))->stop();

### Pi-Somfy part end 
    
````
