### ISSUE TITLE
Cover down timer inacurate on Shelly 2.5

### ISSUE THREAD

**Issue by Basti-Fantasti** [evgeni/esphome-somfy#5]
Hi,

thanks for sharing your awesome configuration templates.
I use your templates on two of my Shelly 2.5

The opening time in the morning which is configured using a substitution in the implementation yaml for sprecific device works very accurate.

I changed the same for the closing time. Therefore I added another substitution for **close_time** to my implementation file and replaced the line of code in the shelly25.yaml

```
substitutions:
  open_time: '0 0 7 * * *'
  close_time: '0 0 22 * * *'

````

```
on_time:
      - cron: '0 0 21 * * *'
        then:
          if:
            condition:
              switch.is_off: ignore_schedule
            then:
              cover.close: rolladen
      - cron: ${open_time}
        then:
          if:
            condition:
              switch.is_off: ignore_schedule
            then:
              cover.open: rolladen



```

to this

```

on_time:
      - cron: ${close_time}
        then:
          if:
            condition:
              switch.is_off: ignore_schedule
            then:
              cover.close: rolladen
      - cron: ${open_time}
        then:
          if:
            condition:
              switch.is_off: ignore_schedule
            then:
              cover.open: rolladen

``

But the covers go down at 21:22 instead of 22:00
I've changed the values to later points from 21:30 to 21:45 and then 22:00 but at the configured time the cover down is never triggered...
